config/routes.rb
Rails.application.routes.draw do
  resources :static_pages, only: [:index]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root "static_pages#index"
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
    if params[:search].present?
      @flickr = FlickRaw::Flickr.new
      @photos = flickr.people.getPhotos(get_params)
      @photos.map! { |photo| FlickRaw.url(photo) }
    end
  end

  private

  def get_params
    params.require(:search).permit(:user_id, :per_page).to_h
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FlickrApi</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/static_pages/index.html.erb
<h1><u>Flickr API</u></h1>
<p>Search photos of any user by their id</p>

<%= form_with scope: :search, url: static_pages_path, method: :get do |f| %>
  <%= f.hidden_field :per_page, value: 10%>
  <%= f.label :user_id, "Enter flickr user id: "%>
  <%= f.text_field :user_id%>
  <%= f.submit "Search user photos" %>
<% end %>

<% if @photos.present? %>
  <% @photos.each do |photo| %>
    <br>
    <br>
    <div class="user-photo">
      <img src="<%= photo %>">
    </div>
  <% end %>
<% end %>